title: Code Together, Not Alone
author: Winona Murphy
description: A safe space to fail, try new things, and learn from one another. I hope my mistakes can empower you to make your own.
theme: minima
